name: Make Commit

on:
  push:
    branches:
      - main
  schedule:
    # Runs the job every day at midnight
    - cron: '0 0 * * *'

jobs:
  make_commit:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3 # Updated to latest version supporting Node.js 20

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4 # Updated to latest version
      with:
        python-version: '3.x'

    # Step 3: Install any dependencies (if you have any, otherwise you can remove this step)
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Step 4: Run the Python script
    - name: Run Python script
      run: python your_script.py

    # Step 5: Commit and Push Changes (only if there are changes)
    - name: Commit and Push Changes (if needed)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add log.txt
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "Automated commit at $(date)"
          git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
